### ISSUE TITLE
Curve.Offset() fails to run in all tests

### ISSUE THREAD

**Issue by cdriesler** [tmakin/RhinoCommonUnitTesting#1]
Discussing it [here](https://discourse.mcneel.com/t/curve-offset-and-mstest/66042) too. 

When any version of the method is called, Curve.Offset() doesn't complete and throws "Object reference not set to an instance of an object."

Edit: To clarify, this might not be an issue because of this project, but it's directly related.

**Comment by tmakin** [comment]
Closing this in favour of the discourse thread:
https://discourse.mcneel.com/t/curve-offset-and-mstest/66042/9

Reproduction of the problem here:
https://github.com/tmakin/RhinoCommonUnitTesting/blob/issues/offset/Src/RhinoPlugin.Tests/OffsetTests.cs
